name: airtrafficsim
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7
  - numpy
  - pandas
  - Flask
  - Flask-SocketIO
  - Eventlet
  - cartopy
  - cdsapi
  - xarray
  - openap

  # Test
  - pytest
  - coverage
  - flake8
  - flake8-docstrings

  # Documentation
  - sphinx
  - myst-parser
  - furo
  - numpydoc
  - sphinx-copybutton

  # Client
  # - nodejs
